import { useCallback, useMemo, useRef, useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useProject } from '../context/ProjectContext';
import { renderVideo, generateTextBundle, isLikelySafariFamily } from '../lib/videoRenderer';
import * as bgmModule from '../lib/bgm';
import { checkServerHealth, serverRender as doServerRender, exportBlobAsFile, copyTextToClipboard } from '../lib/serverRender';
import { hasRenderApiBaseUrl } from '../lib/renderApi';
import './GeneratePage.css';

const GeneratePage = () => {
  const navigate = useNavigate();
  const { currentMedia, selectedStyle, textTone, derived, textBundle, setTextBundle, commitVideo } = useProject();

  const [progress, setProgress] = useState(0);
  const [isGenerating, setIsGenerating] = useState(true);
  const [resolution, setResolution] = useState('720p');
  const sortByDate = (list) => [...list].sort((a, b) => {
    const da = a.date || ''; const db = b.date || '';
    return da.localeCompare(db);
  });
  const [orderedMedia, setOrderedMedia] = useState(() => sortByDate(currentMedia));
  const [videoUrl, setVideoUrl] = useState('');
  const [videoBlob, setVideoBlob] = useState(null);
  const [videoMime, setVideoMime] = useState('');
  const [generationError, setGenerationError] = useState('');
  const videoUrlRef = useRef('');

  const [bgmEnabled, setBgmEnabled] = useState(true);
  const [bgmPreset, setBgmPreset] = useState(() => {
    const id = selectedStyle?.id;
    if (id === 'travel') return 'travel';
    if (id === 'couple') return 'couple';
    if (id === 'vintage') return 'vintage';
    return 'warm';
  });
  const [bgmVolume, setBgmVolume] = useState(0.35);
  const [bgmHint, setBgmHint] = useState('');

  const [serverGenerating, setServerGenerating] = useState(false);
  const [serverError, setServerError] = useState('');
  const [serverReachable, setServerReachable] = useState(false);
  const [serverStatusText, setServerStatusText] = useState('');
  const autoServerTriedRef = useRef(false);
  const serverConfirmRef = useRef(false);

  const [saveError, setSaveError] = useState('');
  const [shareNotice, setShareNotice] = useState('');
  const [browserHint, setBrowserHint] = useState('');
  const [settingsChanged, setSettingsChanged] = useState(false);
  const [photoSpeed, setPhotoSpeed] = useState('medium');
  const [orderExpanded, setOrderExpanded] = useState(false);
  const hasAutoGenerated = useRef(false);

  const hasRenderApi = hasRenderApiBaseUrl();
  const isSafari = isLikelySafariFamily();
  const isWeChat = useMemo(() => /MicroMessenger/i.test(navigator.userAgent), []);

  // Init text bundle
  useEffect(() => {
    if (!textBundle.title) setTextBundle(generateTextBundle(textTone, derived));
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { setOrderedMedia(sortByDate(currentMedia)); }, [currentMedia]);

  useEffect(() => { if (isSafari && resolution !== '720p') setResolution('720p'); }, [isSafari, resolution]);

  useEffect(() => { return () => { if (videoUrlRef.current) URL.revokeObjectURL(videoUrlRef.current); }; }, []);

  // --- Reset helpers ---
  const resetVideoState = useCallback(() => {
    setGenerationError(''); setBgmHint(''); setSaveError(''); setShareNotice('');
    setBrowserHint('');
    setProgress(0); setIsGenerating(true);
    if (videoUrlRef.current) URL.revokeObjectURL(videoUrlRef.current);
    videoUrlRef.current = ''; setVideoUrl(''); setVideoBlob(null); setVideoMime('');
  }, []);

  // --- Client-side render ---
  const generateVideo = useCallback(async () => {
    resetVideoState();
    const result = await renderVideo({
      orderedMedia, resolution, textBundle, textTone, styleId: selectedStyle?.id || '',
      bgmEnabled, bgmVolume, bgmPreset, photoSpeed,
      onProgress: setProgress, bgmModule
    });
    if (!result) {
      setGenerationError(isSafari
        ? '视频生成失败：Safari 没有返回可用视频数据。建议先关闭低电量模式、只选少量照片重试；如果仍失败，请改用桌面端生成后在手机查看结果。'
        : '视频生成失败。建议换用系统浏览器中的 Safari / Chrome，或改用桌面端继续生成。');
      setIsGenerating(false);
      return;
    }
    const url = URL.createObjectURL(result.blob);
    videoUrlRef.current = url;
    setVideoBlob(result.blob); setVideoUrl(url); setVideoMime(result.mimeType);
    commitVideo(result.blob, result.mimeType, url);
    setProgress(100); setIsGenerating(false);
  }, [orderedMedia, resolution, textBundle, textTone, selectedStyle?.id, bgmEnabled, bgmVolume, bgmPreset, photoSpeed, isSafari, resetVideoState, commitVideo]);

  // --- Server-side render ---
  const handleServerRender = useCallback(async () => {
    resetVideoState();
    setServerError(''); setServerStatusText(''); setServerGenerating(true);

    if (!serverConfirmRef.current) {
      const ok = window.confirm('将把你选择的素材上传到已配置的辅助渲染服务进行合成，仅用于本次生成。是否继续？');
      if (!ok) { setIsGenerating(false); setServerGenerating(false); return; }
      serverConfirmRef.current = true;
    }

    const result = await doServerRender({
      orderedMedia, resolution, bgmEnabled, bgmVolume,
      onProgress: setProgress, onStatus: setServerStatusText
    });

    if ('error' in result) {
      setServerError(result.error); setIsGenerating(false); setServerGenerating(false); setServerStatusText('');
      return;
    }

    const url = URL.createObjectURL(result.blob);
    videoUrlRef.current = url;
    setVideoBlob(result.blob); setVideoUrl(url); setVideoMime(result.mimeType);
    commitVideo(result.blob, result.mimeType, url);
    setProgress(100); setIsGenerating(false); setServerGenerating(false); setServerStatusText('');
  }, [orderedMedia, resolution, bgmEnabled, bgmVolume, resetVideoState, commitVideo]);

  const handleDownload = () => {
    if (!videoBlob) return;
    exportBlobAsFile(videoBlob, `memoir.${videoMime.includes('mp4') ? 'mp4' : 'webm'}`);
  };

  const handleShare = async () => {
    try {
      if (!videoBlob) { setSaveError('请先生成视频后再分享。'); return; }
      const title = textBundle.title || '我的回忆录';
      const text = `${currentMedia.length} 个片段 · ${selectedStyle?.name ?? '回忆录作品'}`;
      const ext = videoMime.includes('mp4') ? 'mp4' : 'webm';
      const file = new File([videoBlob], `memoir.${ext}`, { type: videoMime || `video/${ext}` });

      const canShareFile = navigator.share && navigator.canShare && navigator.canShare({ files: [file] });
      if (canShareFile) {
        await navigator.share({ title, text, files: [file] });
        setShareNotice('分享面板已打开。');
        return;
      }
      if (navigator.share) {
        await navigator.share({ title, text });
        setShareNotice('分享面板已打开。');
        return;
      }
      // Desktop fallback: copy a message
      await copyTextToClipboard(`${title}\n${text}\n（视频已保存到本地，文件：memoir.${ext}）`);
      setShareNotice('分享文案已复制到剪贴板。');
    } catch (err) {
      if (err?.name === 'AbortError') return;
      setSaveError(err.message || '分享失败。');
    }
  };

  const handleMove = (index, dir) => {
    setOrderedMedia(prev => {
      const next = [...prev]; const to = index + dir;
      if (to < 0 || to >= next.length) return prev;
      [next[index], next[to]] = [next[to], next[index]];
      return next;
    });
    setSettingsChanged(true);
  };

  const handleRegenerate = () => {
    if (!window.confirm('确定要重新生成视频吗？')) return;
    setSettingsChanged(false);
    generateVideo();
  };

  // --- Auto-start on mount ---
  useEffect(() => {
    if (!hasRenderApi) return;
    checkServerHealth().then(ok => setServerReachable(ok)).catch(() => setServerReachable(false));
  }, [hasRenderApi]);

  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (isWeChat) {
      setGenerationError('微信内置浏览器通常无法稳定本地生成视频。建议点击右上角用系统浏览器打开后再生成。');
      setBrowserHint('推荐在手机系统浏览器中打开本页。');
      setIsGenerating(false);
      if (hasRenderApi && serverReachable && !autoServerTriedRef.current) { autoServerTriedRef.current = true; handleServerRender(); }
      return;
    }
    hasAutoGenerated.current = true;
    generateVideo();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ========= RENDER =========
  return (
    <div className="generate-container">
      <header className="generate-header">
        <button className="back-button" onClick={() => navigate('/style')}>←</button>
        <h1>生成视频</h1>
      </header>
      <main className="generate-main">
        {isGenerating ? (
          <div className="generating-section">
            <div className="progress-container">
              <div className="progress-bar"><div className="progress-fill" style={{ width: `${progress}%` }}></div></div>
              <p className="progress-text">生成中... {progress}%</p>
            </div>
            <div className="generating-tips">
              <p>正在智能分析照片...</p>
              <p>正在应用{selectedStyle?.name}风格效果...</p>
              <p>正在合成视频...</p>
              {serverStatusText && <p>{serverStatusText}</p>}
            </div>
            <div className="generating-media">
              <h3>正在处理的媒体</h3>
              <div className="media-preview-grid">
                {currentMedia.slice(0, 6).map(media => (
                  <div key={media.id} className="media-preview-item">
                    <img src={media.type === 'photo' ? media.url : 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=video%20thumbnail&image_size=square'} alt="媒体预览" />
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="preview-section">
            <div className="video-preview">
              {videoUrl ? (
                <video className="video-player" src={videoUrl} controls playsInline />
              ) : (
                <div className="preview-placeholder">
                  <p>无法生成视频</p>
                  <p className="preview-info">{generationError || '当前浏览器可能不支持本地录制。'}</p>
                  {browserHint && <div className="server-error">{browserHint}</div>}
                  {hasRenderApi && (
                    <button className="server-generate" onClick={handleServerRender} disabled={serverGenerating}>
                      {serverGenerating ? '辅助渲染中…' : '使用辅助渲染'}
                    </button>
                  )}
                  {serverError && <div className="server-error">{serverError}</div>}
                </div>
              )}
            </div>

            <div className="edit-section">
              <h3>视频编辑</h3>
              <div className="edit-options">
                <button className={`edit-button ${settingsChanged ? 'highlight' : ''}`} onClick={handleRegenerate}>
                  <span className="edit-icon">▶</span> {settingsChanged ? '应用修改并重新生成' : '重新生成'}
                </button>
              </div>
            </div>

            <div className="order-section">
              <div className="order-header" onClick={() => setOrderExpanded(!orderExpanded)}>
                <h3>素材顺序 ({orderedMedia.length} 张) {orderExpanded ? '▾' : '▸'}</h3>
                <select className="resolution-select" value={resolution} onChange={(e) => { setResolution(e.target.value); setSettingsChanged(true); }} onClick={e => e.stopPropagation()}>
                  <option value="720p">720P</option><option value="1080p">1080P</option>
                </select>
              </div>
              {orderExpanded && (
                <div className="order-list">
                  {orderedMedia.map((m, idx) => (
                    <div key={m.id} className="order-item">
                      <img className="order-thumb" src={m.type === 'photo' ? m.url : 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=video%20thumbnail&image_size=square'} alt="素材" />
                      <div className="order-meta"><div className="order-title">{m.type === 'photo' ? '照片' : '视频'} {idx + 1}</div><div className="order-sub">{m.date || m.importedAt || ''}</div></div>
                      <div className="order-buttons">
                        <button className="order-btn" onClick={(e) => { e.stopPropagation(); handleMove(idx, -1); }} disabled={idx === 0}>↑</button>
                        <button className="order-btn" onClick={(e) => { e.stopPropagation(); handleMove(idx, 1); }} disabled={idx === orderedMedia.length - 1}>↓</button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="speed-section">
              <h3>照片停留时长</h3>
              <div className="speed-options">
                <button className={`speed-btn ${photoSpeed === 'fast' ? 'active' : ''}`} onClick={() => { setPhotoSpeed('fast'); setSettingsChanged(true); }}>快 (1.5秒)</button>
                <button className={`speed-btn ${photoSpeed === 'medium' ? 'active' : ''}`} onClick={() => { setPhotoSpeed('medium'); setSettingsChanged(true); }}>中等 (3秒)</button>
                <button className={`speed-btn ${photoSpeed === 'slow' ? 'active' : ''}`} onClick={() => { setPhotoSpeed('slow'); setSettingsChanged(true); }}>慢 (5秒)</button>
              </div>
            </div>

            <div className="music-section">
              <h3>音乐</h3>
              <div className="music-controls">
                <label className="music-toggle"><input type="checkbox" checked={bgmEnabled} onChange={(e) => { setBgmEnabled(e.target.checked); setSettingsChanged(true); }} /> 启用背景音乐</label>
                <select className="music-select" value={bgmPreset} onChange={(e) => { setBgmPreset(e.target.value); setSettingsChanged(true); }} disabled={!bgmEnabled}>
                  <option value="warm">温情</option><option value="couple">甜蜜</option><option value="travel">旅行</option><option value="vintage">怀旧</option>
                </select>
                <div className="music-volume">
                  <input className="music-range" type="range" min="0" max="1" step="0.05" value={bgmVolume} onChange={(e) => { setBgmVolume(Number(e.target.value)); setSettingsChanged(true); }} disabled={!bgmEnabled} />
                  <div className="music-volume-value">{Math.round(bgmVolume * 100)}%</div>
                </div>
              </div>
              {bgmHint && <div className="music-hint">{bgmHint}</div>}
            </div>

            <div className="text-section">
              <div className="text-header">
                <h3>AI 文字</h3>
                <button className="text-regenerate" onClick={() => { setTextBundle(generateTextBundle(textTone, derived)); setSettingsChanged(true); }}>重新生成</button>
              </div>
              <div className="text-field"><div className="text-label">开场标题</div><input className="text-input" value={textBundle.title} onChange={(e) => { setTextBundle(prev => ({ ...prev, title: e.target.value })); setSettingsChanged(true); }} /></div>
              <div className="text-field"><div className="text-label">旁白</div><textarea className="text-textarea" value={textBundle.intro} onChange={(e) => { setTextBundle(prev => ({ ...prev, intro: e.target.value })); setSettingsChanged(true); }} rows={3} /></div>
              <div className="text-field"><div className="text-label">结尾寄语</div><textarea className="text-textarea" value={textBundle.ending} onChange={(e) => { setTextBundle(prev => ({ ...prev, ending: e.target.value })); setSettingsChanged(true); }} rows={2} /></div>
            </div>

            <div className="action-buttons">
              <button className={`action-button save-button ${!videoBlob ? 'disabled' : ''}`} onClick={handleDownload} disabled={!videoBlob}>下载视频到设备</button>
              <button className={`action-button share-button ${!videoBlob ? 'disabled' : ''}`} onClick={handleShare} disabled={!videoBlob}>复制分享链接</button>
            </div>

            <div className="share-status-panel">
              {saveError && <div className="share-status-item error">{saveError}</div>}
              {shareNotice && <div className="share-status-item success">{shareNotice}</div>}
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default GeneratePage;
